-- Criando tabela família

CREATE TABLE tb_familia (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    nomeRF VARCHAR(100) NOT NULL,
    quantidadeIntegrantes INTEGER NOT NULL,
    statusCadastral TINYINT NOT NULL,  
    ultimaAtualizacao DATETIME NOT NULL,
    dataCadastro DATETIME NOT NULL DEFAULT CURRENT_DATE,
    rendaTotal INTEGER NOT NULL,
    rendaPerCapta INTEGER NOT NULL,
    tipoLocalDomicilio TINYINT NOT NULL,  
    tipoEspecieDomicilio TINYINT NOT NULL,  
    quantidadeComodos INTEGER NOT NULL,
    quantidadeComodosDormitorio INTEGER NOT NULL,
    tipoMaterialPisoDomicilio TINYINT NOT NULL,  
    tipoMaterialParedeDomicilio TINYINT NOT NULL,  
    tipoAbastecimentoDomicilio TINYINT NOT NULL,  
    temBanheiro BOOLEAN NOT NULL,
    formaEscoamentoDomicilio TINYINT NOT NULL,  
    tipoDestinoLixoDomicilio TINYINT NOT NULL,  
    tipoIluminacaoDomicilio TINYINT NOT NULL,  
    tipoCalcamentoDomicilio TINYINT NOT NULL,
    valorDespesasEnergia INTEGER NOT NULL,
    valorDespesasAguaEsgoto INTEGER NOT NULL,
    valorDespesasGas INTEGER NOT NULL,
    valorDespesasAlimentacao INTEGER NOT NULL,
    valorDespesasTransporte INTEGER NOT NULL,
    valorDespesasAluguel INTEGER NOT NULL,
    valorDespesasMedicamentos INTEGER NOT NULL,
    tipoGrupoTradicional TINYINT NULL,  
    familiaIndigena BOOLEAN NOT NULL,
    numeroPovoIndigena INTEGER NULL,
    numeroReservaIndigena INTEGER NULL,
    familiaQuilombola BOOLEAN NOT NULL,
    numeroComunidadeQuilombola BOOLEAN NULL,
    quantidadePessoasDomicilio INTEGER NOT NULL,
    quantidadeFamiliasDomicilio INTEGER NOT NULL,
    nomeEstabelecimentoSaude VARCHAR(100) NULL,
    cnesEstabelecimentoSaude INTEGER NULL,
    nomeCrasCreas VARCHAR(100) NULL,
    numeroCrasCreas INTEGER NULL,
    quantidadeInternados0a17 INTEGER NOT NULL,
    quantidadeInternados18a59 INTEGER NOT NULL,
    quantidadeInternadosAcima60 INTEGER NOT NULL,
    familiaRiscoInsegurancaAlimentar BOOLEAN NOT NULL,
    familiaSituacaoRua BOOLEAN NOT NULL,
    enderecoFamilia_id BIGINT NOT NULL,
    FOREIGN KEY(enderecoFamilia_id) REFERENCES tb_endereco(id)
);
