-- Criando Tabela Usuario --
CREATE TABLE tb_usuario (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(5) NOT NULL DEFAULT 'USER',
    nome_completo VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    telefone1 VARCHAR(16),
    telefone2 VARCHAR(16),
    nome_mae VARCHAR(100),
    cor_raca TINYINT,
    possui_deficiencia BOOLEAN,
    cursoMaisElevadoQueFrequentou TINYINT,
    ultimoAnoSerieNoCursoQueFrequentou TINYINT,
    concluiuOCursoQueFrequentou BOOLEAN,
    frequentaEscolaOuCreche BOOLEAN,
    sabeLerEEscrever BOOLEAN,
    trabalhouSemanaAnteriorAEntrevista BOOLEAN,
    estavaAfastadoTrabalhoSemanaAnteriorEntrevista BOOLEAN,
    remuneracaoTrabalhoMesAnteriorEntrevista BOOLEAN,
    teveTrabalhoRemunerado12MesesAnterioresEntrevista BOOLEAN,
    valorRecebidoAjudaOuDoacao INT,
    valorAposentadoriaPensaoBpcLoas INT,
    valorSeguroDesemprego INT,
    valorPensaoAlimenticia INT,
    outrasRendas INT,
    identidade VARCHAR(200),
    tituloDeEleitor VARCHAR(200),
    certidaoDeNascimento VARCHAR(200),
    carteiraDeTrabalho VARCHAR(200),
    tipoRelacaoParentescoRF TINYINT,
    responsavelFamiliar BOOLEAN,
    familia_id INT,
    FOREIGN KEY (familia_id) REFERENCES tb_familia(id)
);

